name: flutter_dsbridge_annotation
description: "A modern cross-platform JavaScript bridge annotation"
version: 0.0.5
homepage: https://github.com/skeyboy/flutter_dsbridge_annotation

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  analyzer: ^7.3.0
  flutter:
    sdk: flutter
  source_gen: ^2.0.0
  dsbridge_flutter: ^1.2.0
  build: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

topics:
  - jsbridge
  - javascript
  - webview
  - wkwebview
  - dsbridge
