# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # tag pattern on pub.dev: 'v{{version}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.7.0'

      - name: Validate package
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish --force
        env:
          PUB_HOSTED_URL: https://pub.dev